services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
    environment:
      - MONGO_URI=${MONGO_URI}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - POSTGRES_URI=${POSTGRES_URI}
      - JINA_API_KEY=${JINA_API_KEY}
      # Add any other required env vars here
    depends_on:
      - rag_api
      - meilisearch

  # Disable local MongoDB service since Atlas is used
  mongodb:
    entrypoint: ["echo", "MongoDB service disabled because Atlas is used"]
    command: []

# No local Postgres service
# Removed local postgres service and pgdata volume 