# Please consult our docs for more info: https://www.librechat.ai/docs/configuration/docker_override

services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
    image: ghcr.io/danny-avila/librechat-dev:latest
    env_file:
      - .env

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PostgresChangeMe
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
