# Please consult our docs for more info: https://www.librechat.ai/docs/configuration/docker_override

services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
    image: ghcr.io/danny-avila/librechat-dev:latest
    env_file:
      - stack.env

    #RAG API
  rag_api:
    container_name: RAG-API
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    restart: always
    environment:
      - DB_HOST=vectordb
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8008:8000"
    depends_on:
      - vectordb
    env_file:
      - stack.env

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
