services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
    environment:
      - MONGO_URI=${MONGO_URI}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      #- POSTGRES_URI=${POSTGRES_URI}
      - JINA_API_KEY=${JINA_API_KEY}
      # Add any other required env vars here
    depends_on:
      - rag_api
      - meilisearch

  # Disable local MongoDB service since Atlas is used
  mongodb:
    entrypoint: ["echo", "MongoDB service disabled because Atlas is used"]
    command: []

  postgres:
    image: pgvector/pgvector:pg16
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "${RAG_PG_PORT}:5432"

# No local Postgres service
# Removed local postgres service and pgdata volume 